# Generated by Django 5.0.6 on 2024-06-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cars',
        ),
    ]
