# Generated by Django 5.0.6 on 2024-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_remove_brand_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
    ]
