# Generated by Django 5.0.6 on 2024-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
            ],
        ),
    ]
