# Generated by Django 5.0.6 on 2024-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
