# Generated by Django 5.0.6 on 2024-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bought_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
